＃此工作流程将全新安装节点依赖项，构建源代码并在不同版本的节点上运行测试
＃有关更多信息，请参见：https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
＃美丽研究院
＃活动入口：京东app首页-美妆馆-底部中间按钮
＃只支持Node.js支持N个京东账号
＃脚本兼容：Node.js
＃的cron 1 7,12,19 * * * jd_beauty.js


名称：东瓜美容院

在：
    ＃推送：
    ＃个     分支：
    ＃          -主要
    时间表：
        - cron的：“ 2 23,4,11 * * * ”
    workflow_dispatch：
职位：
    建立：
        运行：ubuntu-latest

        步骤：
            -用途：actions / checkout @ v1
            -名称：使用Node.js 10.x
              用途：actions / setup-node @ v1
              与：
                  节点版本：10.x
            -名称：npm install
              运行：|
                  npm安装
            -名称：“运行【美丽研究院】”
              运行：|
                  节点Ponysitters_Club_Season.js
              env：
                  JD_COOKIE：$ {{ secrets.JD_COOKIE }}
                  SYNCURL：https : //github.com/dajijiyangmao/UFO/raw/main/HAOYANGMAO/The.Flash/The.Flash/j0d_be0auty.js
                  SCKEY：$ {{ secrets.SCKEY }}
                  BARK_PUSH：$ {{ secrets.BARK_PUSH }}
                  PUSH_KEY：$ {{ secrets.PUSH_KEY }}
                  TG_BOT_TOKEN：$ {{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID：$ {{ secrets.TG_USER_ID }}
                  EFORK：$ {{ secrets.EFORK }}
