＃此工作流程将全新安装节点依赖项，构建源代码并在不同版本的节点上运行测试
＃有关更多信息，请参见：https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

名称：jd_mlyjy

在：
  workflow_dispatch：
  时间表：
    - cron的：' 0 1,5,12 * * * '
  观看：
    类型：[开始]
  repository_dispatch：
    类型：mlyjy
职位：
  建立：

    运行：ubuntu-latest
    如果：github.event.repository.owner.id == github.event.sender.id
    步骤：
      -名称：结帐
        运行：|
          git clone -b master https://github.com/SallyU/fuidvsfjkd.git〜/ scripts
      -名称：使用Node.js 10.x
        用途：actions / setup-node @ v1
        与：
          节点版本：10.x
      -名称：npm install
        运行：|
          cd〜/脚本
          npm安装
      -名称：'运行【京东美丽颜究院👩】'
        运行：|
          cd〜/脚本
          节点jd_mlyjy.js
        env：
          JD_COOKIE：$ {{ secrets.JD_COOKIE }}
          JD_DEBUG：$ {{ secrets.JD_DEBUG }}
          PUSH_KEY：$ {{ secrets.PUSH_KEY }}
          BARK_PUSH：$ {{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN：$ {{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID：$ {{ secrets.TG_USER_ID }}
          BARK_SOUND：$ {{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN：$ {{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET：$ {{ secrets.DD_BOT_SECRET }}
          IGOT_PUSH_KEY：$ {{ secrets.IGOT_PUSH_KEY }}
